const templates = {
  auth: {
    userStory: 'AUTH - Implementar autenticación JWT y control de acceso por roles',
    description: 'Sistema de autenticación mediante credenciales (email/password) con generación de JWT. Control de acceso basado en roles (ADMIN/OPERATOR/VIEWER) usando Spring Security con @PreAuthorize. Cubre AUTH-RF-01, AUTH-RF-02, RNF-01 y RNF-02.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint POST /auth/login que valide credenciales contra BCrypt',
      'Generar JWT con JwtService (incluir exp, roles, userId)',
      'Configurar JwtAuthenticationFilter para validar token en cada request',
      'Verificar firma, formato y expiración del token',
      'Configurar SecurityContext con autoridades del usuario',
      'Implementar RNF-01: Control de acceso basado en roles (ADMIN/OPERATOR/VIEWER)',
      'Configurar Spring Security con @PreAuthorize para endpoints',
      'ADMIN: Acceso completo a todas las funcionalidades',
      'OPERATOR: Gestión de cultivos, lotes y eventos (no gestión de usuarios)',
      'VIEWER: Solo visualización del dashboard',
      'Retornar 401 para token inválido/expirado, 403 para acceso denegado',
      'Validar que solo usuarios con active=true puedan autenticarse',
      'Implementar logout (invalidar token o mantener lista negra)',
      'Escribir tests unitarios de autenticación y seguridad',
    ],
  },
  users: {
    userStory: 'USR - Gestión completa de usuarios',
    description: 'CRUD completo de usuarios con control de roles (ADMIN/OPERATOR/VIEWER), validación de unicidad de email, y eliminación lógica (soft delete). Solo ADMIN puede gestionar usuarios. Cubre USR-RF-01 a USR-RF-05.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint POST /users (solo ADMIN puede crear)',
      'Validar email único antes de crear',
      'Encriptar contraseña con BCrypt',
      'Asignar rol por defecto (VIEWER) si no se especifica',
      'Crear endpoint GET /users (solo ADMIN/OPERATOR)',
      'Crear endpoint GET /users/{id}',
      'Crear endpoint PUT /users/{id} (actualización parcial)',
      'Validar email único si se modifica',
      'Permitir cambiar rol y estado active',
      'Crear endpoint DELETE /users/{id} (soft delete: active=false)',
      'Validar que solo usuarios activos pueden autenticarse',
      'Proteger endpoints con @PreAuthorize("hasRole(\'ADMIN\')")',
      'Escribir tests unitarios de usuario',
    ],
  },
  crops: {
    userStory: 'CRP - Gestión de cultivos',
    description: 'Catálogo de cultivos con parámetros de crecimiento (inactivityDaysThreshold, estimatedGrowthDays), validación de unicidad del nombre. Cubre CRP-RF-01 a CRP-RF-06.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint POST /crops (ADMIN/OPERATOR)',
      'Validar nombre único de cultivo',
      'Validar campos obligatorios: name, inactivityDaysThreshold (>0), estimatedGrowthDays (>0)',
      'Crear endpoint GET /crops (todos los usuarios autenticados)',
      'Crear endpoint GET /crops/{id}',
      'Crear endpoint PUT /crops/{id} (actualización parcial)',
      'Validar nombre único si se modifica',
      'Crear endpoint DELETE /crops/{id} (ADMIN/OPERATOR)',
      'Manejar eliminación en cascada a lotes asociados',
      'Validar valores positivos en actualización',
      'Escribir tests unitarios de cultivos',
    ],
  },
  lots: {
    userStory: 'LOT - Gestión completa de lotes con estados dinámicos',
    description: 'Control de lotes dentro del invernadero con cálculo dinámico de estado (CREATED/IN_PRODUCTION/FINISHED), nivel de inactividad (GREEN/YELLOW/RED/GRAY/UNKNOWN), progreso del cultivo (%), y resumen completo. Cubre LOT-RF-01 a LOT-RF-10.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint POST /lots (ADMIN/OPERATOR)',
      'Validar que cropId exista y sea válido',
      'Validar campos obligatorios: name, cropId, startDate',
      'Crear endpoint GET /lots (todos los usuarios)',
      'Crear endpoint GET /lots/{id}',
      'Crear endpoint GET /lots?cropId={id} (filtrar por cultivo)',
      'Crear endpoint PUT /lots/{id} (actualización parcial)',
      'Crear endpoint DELETE /lots/{id} (con cascade a eventos)',
      'Implementar LOT-RF-02: Calcular estado (CREATED/IN_PRODUCTION/FINISHED) según eventos SOWING/HARVEST',
      'Implementar LOT-RF-03: Calcular nivel de inactividad (GREEN/YELLOW/RED/GRAY/UNKNOWN)',
      'Implementar LOT-RF-04: Calcular porcentaje de progreso (%) según estimatedGrowthDays',
      'Implementar LOT-RF-10: Obtener resumen completo del lote (estado, inactividad, progreso, frecuencia, último evento)',
      'Integrar con dashboard para mostrar estados en tiempo real',
      'Escribir tests unitarios de lotes',
    ],
  },
  events: {
    userStory: 'EVT - Registro y gestión completa de eventos agrícolas',
    description: 'Registro y seguimiento de eventos agrícolas (SIEMBRA, COSECHA, RIEGO, FERTILIZACION, etc.) con validación de secuencia, cálculo automático de fecha de cosecha, y filtrado avanzado. Cubre EVT-RF-01 a EVT-RF-07.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint POST /events (ADMIN/OPERATOR)',
      'Validar que lotId, type, userId y timestamp existan',
      'Implementar EVT-RF-02: Validar secuencia (HARVEST sin SOWING → RECHAZAR)',
      'Validar que no haya segundo SOWING',
      'Validar que lote con HARVEST no acepte más eventos',
      'Implementar EVT-RF-03: Calcular fecha estimada de cosecha al registrar SOWING',
      'Crear endpoint GET /events (todos los usuarios)',
      'Crear endpoint GET /events?lotId={id} (filtrar por lote)',
      'Crear endpoint GET /events/{id}',
      'Crear endpoint PUT /events/{id}',
      'Implementar EVT-RF-07: Filtrar por lotId, type, startDate, endDate',
      'Ordenar eventos por timestamp ascendente',
      'Registrar createdAt y userId automáticamente (trazabilidad - RNF-03)',
      'Escribir tests unitarios de eventos',
    ],
  },
  eventTypes: {
    userStory: 'EVT-TYPE - Catálogo de tipos de eventos',
    description: 'Gestión del catálogo de tipos de eventos agrícolas (SOWING, HARVEST, RIEGO, FERTILIZATION, etc.). Cubre EVT-TYPE-RF-01 y EVT-TYPE-RF-02.',
    priority: 'Alta',
    tasks: [
      'Crear endpoint GET /event-types (listar todos los tipos)',
      'Crear endpoint GET /event-types/{id} (obtener por ID)',
      'Definir tipos base: SOWING, HARVEST, WATERING, FERTILIZATION, PESTICIDE, PRUNING, OBSERVATION',
      'Crear endpoint POST /event-types (ADMIN)',
      'Crear endpoint PUT /event-types/{id} (ADMIN)',
      'Crear endpoint DELETE /event-types/{id} (ADMIN)',
      'Validar que tipos existentes no puedan eliminarse si están en uso',
      'Escribir tests de tipos de evento',
    ],
  },
  dashboard: {
    userStory: 'DSH - Dashboard completo con métricas en tiempo real',
    description: 'Visualización de métricas consolidadas del invernadero: gráfico de eventos (últimos 7 días), estados de lotes, nivel de inactividad, progreso de cultivos, y resumen de producción. Cubre DSH-RF-01 a DSH-RF-04.',
    priority: 'Alta',
    tasks: [
      'Implementar DSH-RF-01: Obtener dashboard completo con métricas consolidadas',
      'Crear endpoint GET /dashboard (aceptar opcionalmente cropId)',
      'Implementar DSH-RF-02: Gráfico de eventos últimos 7 días (labels: fechas, values: conteos)',
      'Llenar con 0 los días sin eventos',
      'Implementar DSH-RF-03: Obtener estados de lotes (lotId, lotName, status, inactivityLevel)',
      'Integrar con LotService.getLotStatus() y getInactivityStatus()',
      'Implementar DSH-RF-04: Obtener progreso de lotes (progress, estimatedHarvestDate, sowingDate, daysElapsed, daysRemaining)',
      'Integrar con LotService.getCropProgress() y getLotProgressDetails()',
      'Filtrar por cropId opcionalmente',
      'Mostrar resumen de producción: cultivos activos, cosechas próximas',
      'Integrar con Chart.js para gráficos visuales',
      'Diseñar UI con Angular Material',
      'Escribir tests de integración dashboard',
    ],
  },
};

const moduleMap = {
  'auth': 'auth',
  'autenticación': 'auth',
  'usuarios': 'users',
  'usuario': 'users',
  'cultivos': 'crops',
  'cultivo': 'crops',
  'lotes': 'lots',
  'lote': 'lots',
  'eventos': 'events',
  'evento': 'events',
  'tipos de evento': 'eventTypes',
  'event-types': 'eventTypes',
  'tipos-evento': 'eventTypes',
  'dashboard': 'dashboard',
  'métricas': 'dashboard',
  'metricas': 'dashboard',
};

function getTemplate(moduleName) {
  const normalized = moduleName.toLowerCase().trim();
  const key = moduleMap[normalized];
  return key ? templates[key] : null;
}

module.exports = { templates, moduleMap, getTemplate };